public class AssignmentOperatorsTask{
	public static void main(String[] args){
		String name = "Sindhu";
		String qualification = "B-Tech";
		int lang1 = 74;
		int lang2 = 66;
		int lang3 = 82;
		int sub1 = 46;
		int sub2 = 38;
		int sub3 = 77;
		char gender = 'F';
		String emailId = "sindhu@gmail.com";
		int totalMarks = lang1+lang2+lang3+sub1+sub2+sub3;
		float percentage = (float)totalMarks/(float)6;
		boolean isqualified = true;
			System.out.println("  	");
			System.out.println("Name : "+name);
			System.out.println("Qualification : "+qualification);
			System.out.println("Gender : "+gender);
			System.out.println("E-Mail : "+emailId);
			System.out.println("Total Marks : "+totalMarks);
			System.out.println("Percentage Acquired : "+percentage);
			System.out.println("Is Qualified : "+isqualified);
		String name1 = "Diwakar";
		String qualification1 = "Bio-Tech";
		int lang4 = 74;
		int lang5 = 36;
		int lang6 = 52;
		int sub4 = 46;
		int sub5 = 38;
		int sub6 = 25;
		char gender1 = 'M';
		String emailId1 = "Diwakar@gmail.com";
		int totalMarks1 = lang4+lang5+lang6+sub4+sub5+sub6;
		float percentage1 = (float)totalMarks1/(float)6;
		boolean isqualified1 = true;
			System.out.println("  	");
			System.out.println("Name : "+name1);
			System.out.println("Qualification : "+qualification1);
			System.out.println("Gender : "+gender1);
			System.out.println("E-Mail : "+emailId1);
			System.out.println("Total Marks : "+totalMarks1);
			System.out.println("Percentage Acquired : "+percentage1);
			System.out.println("Is Qualified : "+isqualified1);
		String name2 = "Satya";
		String qualification2 = "B-Tech";
		int lang7 = 24;
		int lang8 = 96;
		int lang9 = 42;
		int sub7 = 76;
		int sub8 = 38;			
		int sub9 = 53;
		char gender2 = 'F';
		String emailId2 = "satya@gmail.com";
		int totalMarks2 = lang7+lang8+lang9+sub7+sub8+sub9;
		float percentage2 = (float)totalMarks2/(float)6;
		boolean isqualified2 = true;
			System.out.println("  	");
			System.out.println("Name : "+name2);
			System.out.println("Qualification : "+qualification2);
			System.out.println("Gender : "+gender2);
			System.out.println("E-Mail : "+emailId2);
			System.out.println("Total Marks : "+totalMarks2);
			System.out.println("Percentage Acquired : "+percentage2);
			System.out.println("Is Qualified : "+isqualified2);
		}
}